### ISSUE TITLE
Week 08 - Day 2 - # Spit and Polish

### ISSUE THREAD

**Issue by mdewey** [Elro1118/assignments#28]
# Spit and Polish

Your GitHub repository will be part of your portfolio and you will likely link to it from your portfolio.

Creating a clean looking README is as important for a project as having nice clean code.

Here are some examples of great READMEs:

- https://github.com/axios/axios
- https://github.com/Microsoft/vscode
- https://github.com/twbs/bootstrap
- https://github.com/electron/electron

Here are some example of great student READMEs:

- https://github.com/cfsanderson/Minesweeper
- https://github.com/m1g/tic-react-toe
- https://github.com/m1g/snowman

## Objectives

- Create quality readmes

### Explorer Mode

- [x] Work on any outstanding homework assignments, focusing on assignments, not so much capstone. 
- [x] Choose several (at least three) repositories to update the READMEs
- [x] Include a description, in your own words, of what the assignment was
- [x] Include a list of technologies (and links to the homepage for each) you used
- [x] Include a link to the project in production (surge, etc.)
- [x] Include a screenshot or an animated gif (see [Kap](https://github.com/wulkano/kap), [Recordit](http://recordit.co/), or [Licecap](https://www.cockos.com/licecap/))
- Optional:
  - [x] Include an aspect you are particularly proud of
  - [x] Include a snippet of code you are proud of (see GitHub Markdown on how to format code snippets)

**Comment by Elro1118** [comment]
https://github.com/Elro1118/moviehouse/blob/master/README.md
https://github.com/Elro1118/octodexinreact/blob/master/README.md
https://github.com/Elro1118/minesweeper/blob/master/README.md

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bceeb145d881263a0f2f05f92594ddf64d6d8c0a/giphy-13.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/78)**__
